service: pdf-generator-service

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    S3_BUCKET: coolgoat-pdf-storage

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:GetObject"
      Resource: "arn:aws:s3:::coolgoat-pdf-storage/*"

functions:
  generatePDF:
    handler: handler.generatePDF
    events:
      - http:
          path: generate-pdf
          method: post

